const PDFDocument = require('pdfkit');
const { formatCurrency, getCurrencySymbol } = require('./currencyConverter');

const generateSalesReport = (sales, user, dateRange, res) => {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });
  
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename=sales-report-${Date.now()}.pdf`);
  doc.pipe(res);

  // Header
  doc.rect(0, 0, 612, 100).fill('#667eea');
  doc.fontSize(28).fillColor('#ffffff').text('Sales Report', 50, 30);
  doc.fontSize(12).text(`${user.businessName || user.name}`, 50, 65);
  doc.fontSize(10).text(`Generated: ${new Date().toLocaleDateString()}`, 400, 35, { align: 'right' });
  if (dateRange) {
    doc.text(`Period: ${dateRange}`, 400, 50, { align: 'right' });
  }
  doc.text(`Currency: ${user.currency}`, 400, 65, { align: 'right' });

  doc.moveDown(3);
  doc.fillColor('#333333');

  // Summary
  const totalRevenue = sales.reduce((sum, s) => sum + s.totalRevenue, 0);
  const totalProfit = sales.reduce((sum, s) => sum + s.profit, 0);
  const totalCost = sales.reduce((sum, s) => sum + s.totalCost, 0);
  const avgMargin = sales.length > 0 ? (sales.reduce((sum, s) => sum + s.profitMargin, 0) / sales.length) : 0;
  const avgROI = sales.length > 0 ? (sales.reduce((sum, s) => sum + s.roi, 0) / sales.length) : 0;

  doc.fontSize(16).fillColor('#667eea').text('Summary', 50, 120);
  doc.moveTo(50, 140).lineTo(562, 140).stroke('#667eea');
  
  doc.fontSize(11).fillColor('#333');
  const summaryY = 150;
  doc.text(`Total Sales: ${sales.length}`, 50, summaryY);
  doc.text(`Total Revenue: ${formatCurrency(totalRevenue, user.currency)}`, 50, summaryY + 18);
  doc.text(`Total Investment: ${formatCurrency(totalCost, user.currency)}`, 50, summaryY + 36);
  doc.text(`Total Profit: ${formatCurrency(totalProfit, user.currency)}`, 300, summaryY);
  doc.text(`Avg Profit Margin: ${avgMargin.toFixed(2)}%`, 300, summaryY + 18);
  doc.text(`Avg ROI: ${avgROI.toFixed(2)}%`, 300, summaryY + 36);

  // Table Header
  const tableTop = summaryY + 70;
  doc.fontSize(14).fillColor('#667eea').text('Sales Details', 50, tableTop);
  doc.moveTo(50, tableTop + 20).lineTo(562, tableTop + 20).stroke('#667eea');

  // Table columns
  const colWidths = [120, 40, 80, 80, 80, 80, 35];
  const headers = ['Product', 'Qty', 'Cost', 'Revenue', 'Profit', 'Margin', 'ROI'];
  let y = tableTop + 30;

  // Header row
  doc.fontSize(9).fillColor('#ffffff');
  doc.rect(50, y - 5, 512, 20).fill('#667eea');
  let x = 55;
  headers.forEach((header, i) => {
    doc.fillColor('#ffffff').text(header, x, y, { width: colWidths[i], align: 'left' });
    x += colWidths[i];
  });
  y += 22;

  // Data rows
  doc.fillColor('#333');
  sales.forEach((sale, index) => {
    if (y > 720) {
      doc.addPage();
      y = 50;
      // Re-add headers
      doc.fontSize(9);
      doc.rect(50, y - 5, 512, 20).fill('#667eea');
      x = 55;
      headers.forEach((header, i) => {
        doc.fillColor('#ffffff').text(header, x, y, { width: colWidths[i], align: 'left' });
        x += colWidths[i];
      });
      y += 22;
      doc.fillColor('#333');
    }

    if (index % 2 === 0) {
      doc.rect(50, y - 3, 512, 18).fill('#f5f5f5');
      doc.fillColor('#333');
    }

    x = 55;
    const row = [
      sale.productName.substring(0, 18),
      sale.quantity.toString(),
      formatCurrency(sale.totalCost, user.currency),
      formatCurrency(sale.totalRevenue, user.currency),
      formatCurrency(sale.profit, user.currency),
      `${sale.profitMargin.toFixed(1)}%`,
      `${sale.roi.toFixed(1)}%`
    ];

    doc.fontSize(8);
    row.forEach((cell, i) => {
      doc.text(cell, x, y, { width: colWidths[i], align: 'left' });
      x += colWidths[i];
    });
    y += 18;
  });

  // Footer
  doc.fontSize(8).fillColor('#999').text(
    'Generated by Sales Dashboard',
    50, 750,
    { align: 'center', width: 512 }
  );

  doc.end();
};

module.exports = { generateSalesReport };